### ISSUE TITLE
Cannot use Passport-Google-Token through POST request on /authentication

### ISSUE THREAD

**Issue by 00Freezy00** [feathersjs/authentication#690] opened 2018-08-01 14:19 UTC
User cannot use Passport-Google-Token through POST request on /authentication.
It works on the previous version of authentication-oauth2 which is the one without the '@'.
### Steps to reproduce

1. Create a feathersjs app using feathersjs cli.

2. Add a users service and google login authentication through cli.

3. Modify the authentication.js and default.json a bit for adapting Passport-Google-Token.
![authentication.js code](https://dl2.pushbulletusercontent.com/b62CfKu8MObtczFLISSffwkuZi7w29fv/Screen%20Shot%202018-07-30%20at%208.27.51%20pm.png)
4. Get Client secret and ID from google api console.
![default.json code](https://dl2.pushbulletusercontent.com/Jvt9hlc7KZT0meS3FPkjZOr2ugsHlfdH/Screen%20Shot%202018-07-30%20at%208.28.15%20pm.png)
5. Get the access token from an app.

6. Post to /authentication with
`{"strategy":"google", "access_token": "google access token"}`

7.  Response
![failed response](https://dl2.pushbulletusercontent.com/SU8FGnx27ROz3v0xupTVM5EXu72P4kpz/Screen%20Shot%202018-07-30%20at%208.27.22%20pm.png)

### Expected behavior
The application should return user a JWT token

### Actual behavior
google strategy is not permitted.

### System configuration

**Module versions** (especially the part that's not working):
@featherjs/authentication: github:feathersjs/authentication
@featherjs/authentication-oauth2: ^1.1.0

**NodeJS version**:
10.7.0

**Operating System**:
Linux inside of nodejs docker image

**Browser Version**:
Postman

**Comment by daffl** [comment] 2018-08-01 16:02
Duplicate of https://github.com/feathersjs/authentication-oauth2/issues/83

**Closed by daffl** 2018-08-01 16:02 UTC
