### ISSUE TITLE
Patching entity through service causes the socket entity to be wrongly updated

### ISSUE THREAD

**Issue by claustres** [feathersjs/authentication#706] opened 2018-10-10 10:00 UTC
Referenced in new mono repo as well under https://github.com/feathersjs/feathers/issues/1049 but added here to be addressed by PR.

**Comment by daffl** [comment] 2018-10-16 15:58
Duplicate of https://github.com/feathersjs/feathers/issues/1049

**Closed by daffl** 2018-10-16 15:58 UTC
