### ISSUE TITLE
Login method is invoked twice in channels.js file

### ISSUE THREAD

**Issue by rondaniel00** [feathersjs/authentication#673] opened 2018-05-16 17:27 UTC
Login method is invoked twice in channels.js file.
app.on('login', (authResult, { connection }) => { // CALLED TWICE  } ));

Verified that  client.authenticate() is called only once.

**Comment by marshallswain** [comment] 2018-05-18 13:44
@rondaniel00 I believe you mentioned that there was something specific to your app with this issue?  Is that for sure the case?

**Comment by daffl** [comment] 2018-05-18 16:13
I can confirm that this seems to be happening everywhere. Try the [feathers-chat](https://github.com/feathersjs/feathers-chat) logging the `login` event. When refreshing the chat page (once authenticated) it will show up twice.

**Comment by 8BallBomBom** [comment] 2018-05-19 12:02
Also experiencing this.
Thought i had something acting up on my client.

**Comment by koraniar** [comment] 2018-08-24 19:15
I have the same problem and I verified that client.authenticate() is called only once

**Comment by ricardopolo** [comment] 2018-08-30 16:33
I think this may be related, that the feathers cliente default behavior stabilsih the conecction using long pooling and the upgrade to websockets...

@koraniar would you test modifying the feathers client parameters to see how if is that the root cause?

**Comment by daffl** [comment] 2019-01-18 20:52
Duplicate of https://github.com/feathersjs/feathers/issues/1174, will be tracked there.

**Closed by daffl** 2019-01-18 20:52 UTC
