### ISSUE TITLE
Custom JWT payload is not set in context.params.payload

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs/authentication#682] opened 2018-06-12 01:48 UTC
### Steps to reproduce
This repo has a detailed example of the problem. Start the server, navigate to `http://localhost:3030` and then look at the node console, which will have detailed output of the problem.
[https://github.com/DaddyWarbucks/token-payload](https://github.com/DaddyWarbucks/token-payload)

### Expected behavior
After creating a custom JWT payload, the `context.params.payload` will reflect the proper custom payload

### Actual behavior
The `context.params.payload` only has one prop, `userId`, on it.

**Comment by kmorales13** [comment] 2018-06-13 18:31
Maybe try with:
```
Object.assign(context.params.payload, { accountId });
```

**Comment by daffl** [comment] 2018-06-14 03:20
I can confirm that this is a bug with how socket authentication is currently handled. Will be fixed through #517 in the next version.

**Comment by PrabhuKathiresan** [comment] 2019-01-22 07:59
I could still see that JWT payload is still not set in the context params

As an workaround I am setting the payload in the context params in the before create hooks.

app.service('authentication').hooks({
  before: {
    create(context) {
      context.params.payload = context.data;
    }
  }
});

**Comment by daffl** [comment] 2019-05-08 05:46
Closing since this should be fixed in Feathers v4 authentication as mentioned.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).

**Closed by daffl** 2019-05-08 05:46 UTC
