### ISSUE TITLE
Missing `request.url` in the request given to passport for authentication

### ISSUE THREAD

**Issue by jawadst** [feathersjs/authentication#494] opened 2017-04-29 17:23 UTC
### Steps to reproduce
I am using the latest from feathers-authentication and feathers-authentication-jwt and I am allowing the JWT token to be read from the URL.

My configuration looks like:
```
app.configure(authentication({
        secret: 'blablabla',
        jwt: {
          jwtFromRequest: ExtractJwt.fromExtractors([ // a passport-jwt option determining where to parse the JWT
            ExtractJwt.fromAuthHeaderWithScheme('Bearer'), // Allowing "Bearer" prefix
            ExtractJwt.fromHeader('Authorization'), // From "Authorization" header
            ExtractJwt.fromUrlQueryParameter('token') // From query-string parameter "token"
          ])
        }
      }))
      .configure(authenticationJwt({ Verifier: verifier }))
```

### Expected behavior
I expect Passport to correctly extract the token from the URL if I go to "http://url?token=mytoken".

### Actual behavior
Instead of the token being picked up, I get the following error: "Parameter "url" must be a string, not undefined"

When looking into the debug logs, I see:
```
feathers - authentication: passport: authenticate Passport request object {
    query: {},
    body: {},
    params: {
        query: {
            format: 'csv',
            action: 'export',
            token: 'hiddentoken',                                           
            file_id: '5904c80eb1e9ae0b7a9916de'
        },
        file_id: '5904c80eb1e9ae0b7a9916de',
        provider: 'rest',
        headers: {
            host: '127.0.0.1:45079',
            'accept-encoding': 'gzip, deflate',
            'user-agent': 'node-superagent/3.5.2',
            connection: 'close'
        }
    },
    headers: {
        host: '127.0.0.1:45079',
        'accept-encoding': 'gzip, deflate',
        'user-agent': 'node-superagent/3.5.2',
        connection: 'close'
    },
    cookies: {},
    session: {}
}
```

There is no `url` parameter on the request object and it is expected by JWT for that extractor (https://github.com/themikenicholson/passport-jwt/blob/master/lib/extract_jwt.js#L42).

### System configuration

**Module versions** (especially the part that's not working):
Latest for authentication and authentication-jwt

**NodeJS version**:
7+ ; I am using superagent/supertest as my client for testing

**Operating System**:
Linux

**Comment by loris** [comment] 2017-06-26 14:45
+1, had to use a custom extractor instead:

```
const extractJwtFromQuery = key => ({ params }) => {
  const token = params.query[key];
  if (token) {
    delete params.query[key];
    return token;
  }
};
```

**Comment by ekryski** [comment] 2017-07-05 01:02
Sounds good. I'll try and tackle this soon.

**Comment by DesignByOnyx** [comment] 2017-10-10 23:39
This is a greater problem related to this code: https://github.com/feathersjs/feathers-authentication/blob/e7f6d6f5545746c28d9d4440607f85dbd1e3bac6/src/hooks/authenticate.js#L46

The problem is that it's not the _real_ request object, but rather something that _looks_ like the request object. In my case I am needing to get the users IP address to do some custom verifications and validations:

```js
const ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
```

I was able to get around this by cheating, but shouldn't need to do this:

```js
// TODO: remove this middleware (see verifier function as well)
app.use((req, res, next) => {
  // expose whatever you need here
  req.feathers.connection = req.connection;
  req.feathers.url = req.url;
});
// then set up authentication
app.use(authentication);
app.use(jwt({ Verifier: CustomVerifier }));
```

The data exposed on `app.feathers` is later available on `req.params` inside the verifier function. I copied it back like this:
```js
class CustomVerifier extends Verifier {
  verify (req, payload, done) {
    req.connection = req.params.connection;
    req.url = req.params.url;
    ...
    done(null, user);
  }
};
```

**Comment by ekryski** [comment] 2017-10-15 02:00
@DesignByOnyx ya I think you are right that we probably need to also pass the `url` and the `connection` object. The way you are doing it isn't necessarily wrong as that is the recommended way to pass stuff to services, hooks, etc. from Express. However it definitely feels like a hack.

The request object is indeed a faked out one. This is sort of the "magic" behind feathers-authentication in order to allow passport to JustWork™ across middleware, hooks, sockets, etc. We have to fake out a request object so that passport plays nicely.

I'm fine with augmenting the fake "request" object with more data. I'd like @daffl to weigh in on whether that is going to mess up the engine agnostic work he's been doing as this might be starting to couple us even tighter to Express.

**Comment by DesignByOnyx** [comment] 2017-10-16 18:36
Thanks @ekryski - The biggest consideration with all of this is the the portability of passport code. In my situation, I had existing code which had been working as "plain middleware" for the past year. When converting it to a custom passport verifier (for use with [this plugin](https://github.com/DesignByOnyx/feathers-authentication-custom)), things broke in a very mysterious way because the `req` object was not really a `req` object. The same thing would happen for any other passport users who use a custom Verifier code which relies on `req` data.

**Comment by ekryski** [comment] 2017-10-18 22:07
Was just discussing with @daffl. @DesignByOnyx what was the reason that you needed to do this?

```js
req.connection = req.params.connection;
req.url = req.params.url;
```

**Comment by ekryski** [comment] 2017-10-18 22:49
On another note. I can patch this in pretty quick here, so it will at least work and close out this issue. Sorry for the delay @DesignByOnyx and @jawadst

**Comment by DesignByOnyx** [comment] 2017-10-19 01:54
I am using a shared module to validate the request - the module is meant to work as connect/express middleware and expects a `req` object. Internally it uses the user's IP address and a cookie to validate the user against a 3rd party SSO service. I included `req.url` in my code above so that it would be relevant to the OP.

Since you are going to be digging into the code, it might be worthwhile to go ahead and add as many properties as possible to the "fake" request object - as many as you can to make it interoperable with AJAX and sockets.

**Comment by dekelev** [comment] 2017-11-19 14:12
I've got a similar use case. I have FeathersJS app with JWT authentication using custom JWT verifier class. I have a requirement to add guest users that can interact with few services, so I've added the guest users logic using the regular users logic with few minor exceptions, such as generating JWT token with shorter expiration for guest users.

I now need to limit guest users from using all the services (that requires auth) except for few specific services. I wanted to add this flow to my custom JWT verifier class, but even though I can detect a guest user rather easily, I'm unable to get the service or URL that the user requested in that point.

**Comment by daffl** [comment] 2017-11-19 18:03
@dekelev There isn't really a need to muck with the standard authentication mechanism for that. It can be much easier checked in a `before` application hook by checking the `path` and comparing what is set in `hook.params.user` (or whichever entity you chose).

**Comment by dekelev** [comment] 2017-11-19 18:46
Thanks @daffl, I think your suggestion is a much cleaner solution, though it does come with a little penalty, which is the access to DB for fetching the user record. In my approach, I added a boolean "guest" property to the JWT payload in order to avoid DB access for just figuring out if the user is guest or not.

**Closed** 2019-05-08 05:41 UTC
Labels: Bug
